version: '1.0.{build}'

image: Visual Studio 2017

platform:
  - x64

configuration:
  - Release
  - Debug

build_script:
  - mkdir build
  - cd build
  - cmake --version
  - cmake ..
  - cmake --build .