version: '1.0.{build}'

image: Visual Studio 2017

platform:
  - x64

configuration:
  - Release
  - Debug

install:
  - set QTDIR=C:\Qt\5.15.1\mingw53_32
  - set PATH=%PATH%;%QTDIR%\bin;C:\MinGW\bin

build_script:
  - mkdir build
  - cd build
  - cmake --version
  - cmake ..
  - cmake --build .