version: '1.0.{build}'

image: Visual Studio 2017

environment:
  CMAKE_INSTALL_ROOT: C:\projects\cmake
  matrix:
    - build_name: mingw73_32_qt5_15_1
      QTPATH: C:\Qt\5.15.1\mingw73_32
      MINGW32: C:\Qt\Tools\mingw730_32

platform:
  - x64

configuration:
  - Release
  - Debug

install:
  - mkdir %CMAKE_INSTALL_ROOT%
  - cd %APPVEYOR_BUILD_FOLDER%
  - set PATH=%PATH%;%CMAKE_INSTALL_ROOT%;%QTPATH%\bin;%MINGW32%\bin

build_script:
  - mkdir build
  - cd build
  - cmake --version
  - cmake .. -G "Unix Makefiles" -DCMAKE_MAKE_PROGRAM=mingw32-make
  - mingw32-make